# Gush configuration file, any comments will be lost.
meta-header: "This file is part of the RollerworksNavigationBundle package.\n\n(c) Sebastiaan Stok <s.stok@rollerscapes.net>\n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
table-pr:
    bug_fix: ['Bug Fix', 'no']
    new_feature: ['New Feature', 'no']
    deprecations: [Deprecations, 'no']
    fixed_tickets: ['Fixed Tickets', '']
    license: [License, MIT]
pr_type:
    - feature
    - bug
    - refactor
    - style
    - doc
    - security
repo_adapter: github
issue_tracker: github
repo_org: rollerworks
repo_name: NavigationBundle
issue_project_org: rollerworks
issue_project_name: NavigationBundle
